version: "3.7"
services:
  mmpose:
    container_name: "mmpose"
    image: "mmpose-mmpose:latest"
    restart: always
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    shm_size: "26gb"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
